# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.


"""

!pip install spacy==3.7.5 numpy==1.26.4 spacypdfreader 'spacypdfreader[pytesseract]' requests indra

!python -m spacy download en_core_web_sm

# Install SciSpacy Models
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_md-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_jnlpba_md-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_craft_md-0.5.4.tar.gz
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz

import spacy
import re
import requests
from spacypdfreader import pdf_reader
from indra.databases import hgnc_client
from difflib import get_close_matches
import difflib

# ==========================================
# 1. Pre-Processing Functions
# ==========================================

#Removes page numbers from extracted PDF text.
def remove_page_numbers(text):
    return re.sub(r'\n\d+\n', '\n', text)

#Rejoins words that were split across lines with a hyphen.
def fix_hyphenated_words(text):
    return re.sub(r'(\w+)-\n(\w+)', r'\1\2', text)

# Break multiple whitespace characters into a single space.
def normalize_whitespace(text):
    return re.sub(r'\s+', ' ', text).strip()


#Corrects common OCR misrecognition errors such as O for 0 and I for 1.
def correct_ocr_errors(text):
    corrections = {
        '0': 'O',
        '1': 'I',
    }
    for wrong, correct in corrections.items():
        text = text.replace(wrong, correct)
    return text

#Strips non-alphanumeric and non-whitespace characters from text.
def remove_special_characters(text):
    return re.sub(r'[^\w\s]', '', text)

# Remove email address from text
def remove_email_addresses(text):
    email_regex = r'[\w\.-]+@[\w\.-]+\.\w+'
    return re.sub(email_regex, '', text)

#Removes four digit years and all caps section headings from text such as - RESULTS, DISCUSSIONS, INTRODUCTIONS , citation years
def remove_years_and_section_titles(text):
    text = re.sub(r'\d{4}', '', text)
    text = re.sub(r'[A-Z][A-Z0-9\s]+:', '', text)
    text = re.sub(r'\d+\.\s+[A-Z][A-Z0-9\s]+', '', text)
    text = re.sub(r'[A-Z][A-Z0-9\s]+', '', text)
    return text

#a pipeline of cleaning steps to raw PDF-extracted text.
def preprocess_text(ocr_text):

    # cleaned_text = remove_years_and_section_titles(ocr_text)
    # cleaned_text = remove_email_addresses(cleaned_text)

    cleaned_text = remove_page_numbers(ocr_text)
    # cleaned_text = fix_hyphenated_words(cleaned_text)
    cleaned_text = normalize_whitespace(cleaned_text)
    # cleaned_text = correct_ocr_errors(cleaned_text)
    cleaned_text = remove_special_characters(cleaned_text)
    return cleaned_text

#emoves stray punctuation characters from a list of string tokens
def clean_list(some_list):
    cleaned_list = []
    for item in some_list:
        item = re.sub(r"[',]", '', item).strip()
        cleaned_list.append(item)
    return cleaned_list



# 2. Database Verification Functions


#Verifies protein names against the HGNC
# Returns : List of Standardized HGNC gene names
# Returns : Fuzzy Suggestions
def verify_proteins_using_HGNC(protein_list):
    exact_matches = []
    fuzzy_suggestions = {}

    for protein in protein_list:
        # Strict length filter we exclude anything 3 chars or less
        if len(protein) <= 3:
            print(f"Skipping '{protein}' — too short.")
            continue
        try:
            hgnc_id = hgnc_client.get_hgnc_id(protein)
            if hgnc_id:
                standard_name = hgnc_client.get_hgnc_name(hgnc_id)
                if standard_name:
                    exact_matches.append(standard_name)
            else:
                # Did not find the protein now attempt fuzzy suggestion
                all_hgnc_names = [
                    hgnc_client.get_hgnc_name(hid)
                    for hid in hgnc_client.hgnc_names.keys()
                    if hgnc_client.get_hgnc_name(hid)
                ]
                close_matches = get_close_matches(protein, all_hgnc_names, n=3, cutoff=0.8)
                if close_matches:
                    fuzzy_suggestions[protein] = close_matches
                    print(f"[HGNC] '{protein}' not verified. Suggestions: {close_matches}")
                else:
                    print(f"[HGNC] '{protein}' not found. No suggestions.")
        except Exception as e:
            print(f"[HGNC] Error processing '{protein}': {e}")

    return list(set(exact_matches)), fuzzy_suggestions



# Verify the extracted text using UniProt
# send batched REST API requests
# Returns : List of Standardized protein names that matched UniProt.
# Returns : Fuzzy Suggestions
def verify_proteins_uniprot_version_1(protein_list, reviewed=True, batch_size=50, similarity_threshold=0.8):
    url = "https://rest.uniprot.org/uniprotkb/search"
    exact_matches = []
    fuzzy_suggestions = {}

    for i in range(0, len(protein_list), batch_size):
        batch = [p for p in protein_list[i:i + batch_size] if len(p) > 3]  # length filter

        if not batch:
            continue

        query = " OR ".join(f'gene:"{protein}"' for protein in batch)
        params = {
            'query': query,
            'fields': 'accession,id,protein_name,gene_names',
            'format': 'json'
        }
        if reviewed:
            params['reviewed'] = 'true'

        try:
            response = requests.get(url, params=params)

            if response.status_code == 200:
                data = response.json().get('results', [])

                # Collect all gene names from entire batch response for fuzzy pool
                all_returned_gene_names = []
                exact_matched_proteins = set()

                for entry in data:
                    gene_names = []
                    for gene in entry.get('genes', []):
                        gene_name = gene.get('geneName', {})
                        if isinstance(gene_name, dict):
                            gene_names.append(gene_name.get('value', ''))
                            synonyms = gene.get('synonyms', [])
                            if isinstance(synonyms, list):
                                gene_names.extend([syn.get('value', '') for syn in synonyms if isinstance(syn, dict)])

                    gene_names = [name.strip().upper() for name in gene_names if name]
                    all_returned_gene_names.extend(gene_names)

                    for protein in batch:
                        if protein.upper() in gene_names:
                            exact_matches.append(protein)
                            exact_matched_proteins.add(protein)

                # Fuzzy matching only for proteins that didn't get exact match
                fuzzy_pool = list(set(all_returned_gene_names))
                for protein in batch:
                    if protein not in exact_matched_proteins:
                        close_matches = difflib.get_close_matches(
                            protein.upper(),
                            fuzzy_pool,
                            n=3,
                            cutoff=similarity_threshold
                        )
                        if close_matches:
                            fuzzy_suggestions[protein] = close_matches
                            print(f"[UniProt] '{protein}' not verified. Suggestions: {close_matches}")
                        else:
                            print(f"[UniProt] '{protein}' not found. No suggestions.")
            else:
                print(f"Error {response.status_code} for batch starting with '{batch[0]}': {response.text}")

        except Exception as e:
            print(f"Request failed for batch starting with '{batch[0]}': {e}")

    return list(set(exact_matches)), fuzzy_suggestions

# Manages Protein Verification across UniProt and HGNC.
# Combines and deduplicates exact matches from both databases
# Combines fuzzy suggestions from both datatsets.
# retruns : Deduplicated list of strictly verified protein names from either or both databases.
# retruns: Suggested Correct Names for Manual Review.

def protein_processor(protein_list):
  # Since protein names are usually capital lettered.
    protein_list_upper = [item.upper() for item in protein_list]

    print("Verifying against UniProt")
    uniprot_exact, uniprot_fuzzy = verify_proteins_uniprot_version_1(protein_list_upper, reviewed=True)

    print("*****")

    print("Verifying against HGNC")
    hgnc_exact, hgnc_fuzzy = verify_proteins_using_HGNC(protein_list_upper)

    # List 1: Strict verified — union of exact matches from both databases
    final_verified = list(set(uniprot_exact + hgnc_exact))

    # List 2: Fuzzy suggestions which is an union of fuzzy matches from both databases
    # If a protein appears in both, merge their suggestions
    all_fuzzy = {}
    for protein, suggestions in {**uniprot_fuzzy, **hgnc_fuzzy}.items():
        if protein in final_verified:
            continue  # already exactly verified, skip
        if protein in all_fuzzy:
            all_fuzzy[protein] = list(set(all_fuzzy[protein] + suggestions))
        else:
            all_fuzzy[protein] = suggestions

    print(f"\n RESULTS ")
    print(f"UniProt exact matches : {len(uniprot_exact)}")
    print(f"HGNC exact matches    : {len(hgnc_exact)}")
    print(f"Final verified list   : {len(final_verified)}")
    print(f"Flagged for manual review : {len(all_fuzzy)}")

    print(f"\n--- Final Verified Proteins ---")
    for p in final_verified:
        print(f"  {p}")

    print(f"\n--- Flagged for Manual Review ---")
    for protein, suggestions in all_fuzzy.items():
        print(f"  {protein} -> possible matches: {suggestions}")

    return final_verified, all_fuzzy


# 3. Main Execution Block


if __name__ == "__main__":
    pdf_path = "/content/dey_bishai_2014_Mtb_host_interaction-1.pdf"
    print(f"Reading PDF: {pdf_path}...")

    #Load basic Spacy model and parse PDF
    nlp_base = spacy.load("en_core_web_sm")
    doc = pdf_reader(pdf_path, nlp_base)
    raw_text = doc.text  # Extract the string text from the parsed document

    # Preprocess text
    print("Preprocessing text...")
    preprocessed_text = preprocess_text(raw_text)

    # Load SciSpacy NER Models
    print("Loading SciSpacy Models...")
    nlp_sci_md = spacy.load("en_core_sci_md")
    models = [
        spacy.load("en_ner_jnlpba_md"),
        spacy.load("en_ner_bc5cdr_md"),
        spacy.load("en_ner_bionlp13cg_md"),
        spacy.load("en_ner_craft_md")
    ]

    # First Iteration: Find proteins
    print("Extracting entities (Iteration 1)...")
    docs_iter_1 = [model(preprocessed_text) for model in models]

    proteins = []
    #target_labels = {"PROTEIN", "CHEBI", "RNA", "GENE_OR_GENE_PRODUCT"}
    target_labels = {
    "GGP",
    "PROTEIN",
    "RNA",
    "DNA",
    "GENE_OR_GENE_PRODUCT",
}

    for d in docs_iter_1:
        for ent in d.ents:
            if ent.label_ in target_labels:
                proteins.append(ent.text)

    # Clean the list and tokenize
    cleaned_protein_list = clean_list(proteins)

    # 5. Second Iteration: Re-process the extracted entities
    print("Refining entities (Iteration 2)...")
    processed_list_string = ', '.join(cleaned_protein_list)
    docs_iter_2 = [model(processed_list_string) for model in models]

    final_list = []
    for d in docs_iter_2:
        for ent in d.ents:
            if ent.label_ in target_labels:
                final_list.append(ent.text)

    # Remove duplicates because we can have same items from both databases
    unique_final_list = list(set(final_list))
    print(f"Found {len(unique_final_list)} unique potential entities.")

    # 6. Database Verification
    print("Verifying against HGNC and UniProt databases")
    verified_proteins = protein_processor(unique_final_list)

    print("FINAL VERIFIED PROTEINS")
    for p in verified_proteins:
        print(p)



