# -*- coding: utf-8 -*-
"""Recover_Reconcile.ipynb

Automatically generated by Colab.


"""



""" Recover and Repair"""

import subprocess
import sys


def install_dependencies():
    packages = ["indra", "pybel", "networkx", "matplotlib", "pandas", "openpyxl"]
    for pkg in packages:
        subprocess.check_call([sys.executable, "-m", "pip", "install", pkg],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)



# Configuration , add proteins we are interested about.

PROTEIN_ENTITIES = ['STAT1', 'NTM', 'ASIC2', 'TRPV1', 'FER', 'AL', 'TRPM8', 'TRP', 'TRPA1', 'ASIC3', 'IL6']   
OUTPUT_FILE = "protein_interactions.xlsx"



# Step 1 — Fetch statements from PyBel


def fetch_pybel_statements(protein_entities: list) -> list:
    """Fetch statements from PyBEL neighbourhood for the given proteins."""
    from indra.sources import bel as indra_bel

    if not protein_entities:
        print("[PyBEL] protein_entities is empty — skipping PyBEL query.")
        return []
    try:
        processor = indra_bel.process_pybel_neighborhood(protein_entities)
        if processor is None:
            print("[PyBEL] Processor returned None.")
            return []
        statements = processor.statements or []
        print(f"[PyBEL] Retrieved {len(statements)} statement(s).")
        return statements
    except Exception as exc:
        print(f"[PyBEL] Error during processing: {exc}")
        return []

# Step 1.1 Fetch Statements from Pathway Commons
def fetch_biopax_statements(protein_entities: list) -> list:
    """Fetch statements from Pathway Commons (BioPax) for the given proteins."""
    from indra.sources import biopax as indra_biopax

    if not protein_entities:
        print("[BioPax] protein_entities is empty — skipping BioPax query.")
        return []
    try:
        processor = indra_biopax.process_pc_pathsfromto(
            source_genes=protein_entities,
            target_genes=protein_entities,
        )
        if processor is None:
            print("[BioPax] Processor returned None.")
            return []
        statements = processor.statements or []
        print(f"[BioPax] Retrieved {len(statements)} statement(s).")
        return statements
    except Exception as exc:
        print(f"[BioPax] Error during processing: {exc}")
        return []



# Step 2 — Filter statements

# We are only interested in IncreaseAmount , DecreaseAmount , Activation, and Inhibition.
def filter_regulatory_statements(statements: list) -> list:
    """Keep only IncreaseAmount, DecreaseAmount, Activation, and Inhibition."""
    from indra.statements import IncreaseAmount, DecreaseAmount, Activation, Inhibition

    kept_types = (IncreaseAmount, DecreaseAmount, Activation, Inhibition)
    filtered = [stmt for stmt in statements if isinstance(stmt, kept_types)]
    print(f"[Filter] {len(filtered)} regulatory statement(s) after type filter.")
    return filtered


def filter_protein_only_statements(statements: list) -> list:
    """
    Retain only statements where every non-None agent has an all-uppercase
    name (heuristic for protein symbols like EGFR, TP53, etc.).
    """
    protein_statements = []
    for stmt in statements:
        agents = stmt.agent_list()
        non_null_agents = [a for a in agents if a is not None]
        if non_null_agents and all(a.name.isupper() for a in non_null_agents):
            protein_statements.append(stmt)

    print(f"[Filter] {len(protein_statements)} protein-only statement(s) remaining.")
    return protein_statements



# Step 3 — Build graph and remove dead-end nodes


def build_closed_graph(protein_statements: list):
    """
    Build a directed graph with IndraNetAssembler and remove nodes that
    do not both *send* and *receive* at least one interaction (dead-ends).
    Iterates until the graph stabilises (removing one node can create new
    dead-ends). Returns the pruned DiGraph.
    """
    import networkx as nx
    from indra.assemblers.indranet import IndraNetAssembler

    assembler = IndraNetAssembler(statements=protein_statements)
    graph     = assembler.make_model()
    digraph   = nx.DiGraph(graph)   # plain DiGraph for clean degree counting

    while True:
        to_remove = [
            node for node in digraph.nodes
            if digraph.in_degree(node) == 0 or digraph.out_degree(node) == 0
        ]
        if not to_remove:
            break
        digraph.remove_nodes_from(to_remove)

    print(f"[Graph] Closed graph: {digraph.number_of_nodes()} node(s), "
          f"{digraph.number_of_edges()} edge(s).")
    return digraph



# Step 4 — Deduplicate and map interaction types


UPREGULATING   = {"IncreaseAmount", "Activation"}
DOWNREGULATING = {"DecreaseAmount", "Inhibition"}


def map_interaction_type(raw_types: set) -> str:
    """
    Map a set of raw INDRA type names for one (source, target) pair to:
      'upregulates'   — only upregulating types seen
      'downregulates' — only downregulating types seen
      'unsure'        — conflicting directions seen for the same pair
    """
    has_up   = bool(raw_types & UPREGULATING)
    has_down = bool(raw_types & DOWNREGULATING)

    if has_up and has_down:
        return "unsure"
    if has_up:
        return "upregulates"
    return "downregulates"


def build_interaction_table(protein_statements: list, closed_graph) -> list:
    """
    For each statement whose source and target are both in the closed graph,
    collect all raw interaction types per (source, target) pair, deduplicate,
    and map to a single interaction label.
    """
    from collections import defaultdict

    pair_types: dict = defaultdict(set)

    for stmt in protein_statements:
        agents = stmt.agent_list()
        if len(agents) < 2 or agents[0] is None or agents[1] is None:
            continue
        source = agents[0].name
        target = agents[1].name
        if source in closed_graph.nodes and target in closed_graph.nodes:
            pair_types[(source, target)].add(type(stmt).__name__)

    rows = [
        {
            "Source":           source,
            "Target":           target,
            "Interaction Type": map_interaction_type(raw_types),
        }
        for (source, target), raw_types in pair_types.items()
    ]

    print(f"[Table] {len(rows)} unique interaction(s) after deduplication.")
    return rows



# Step 5 — Export to Excel


def export_to_excel(rows: list, filepath: str) -> None:
    import pandas as pd

    if not rows:
        print("[Export] No interactions to export.")
        return

    df = pd.DataFrame(rows, columns=["Source", "Target", "Interaction Type"])
    df.sort_values(["Source", "Target"], inplace=True)
    df.to_excel(filepath, index=False)
    print(f"[Export] Saved {len(df)} row(s) to '{filepath}'.")



# Main


def main():
    if not PROTEIN_ENTITIES:
        print(
            "WARNING: PROTEIN_ENTITIES is empty.\n"
            "Edit the PROTEIN_ENTITIES list at the top of this script and re-run.\n"
            "Example: PROTEIN_ENTITIES = ['BRCA1', 'TP53', 'EGFR']\n"
        )

    # Fetch
    pybel_stmts  = fetch_pybel_statements(PROTEIN_ENTITIES)
    biopax_stmts = fetch_biopax_statements(PROTEIN_ENTITIES)
    combined     = pybel_stmts + biopax_stmts
    print(f"\n[Combined] {len(combined)} total statement(s) before filtering.")

    # Filter
    regulatory   = filter_regulatory_statements(combined)
    protein_only = filter_protein_only_statements(regulatory)

    # Graph
    closed_graph = build_closed_graph(protein_only)

    # Deduplicate & map
    rows = build_interaction_table(protein_only, closed_graph)

    # Export
    export_to_excel(rows, OUTPUT_FILE)

    return rows


if __name__ == "__main__":
    # Uncomment the next line to auto-install dependencies on first run:
    install_dependencies()
    main()